// Code generated by sqlc. DO NOT EDIT.

package dbmysql

import (
	"reflect"
	"strings"
)

const dynQuestionMarkPlaceholders = true

// dynCompiledSeg is one segment of a pre-compiled dynamic SQL query.
type dynCompiledSeg struct {
	// parts splits the segment text at each numbered $N or ?N input placeholder.
	// Build renders active placeholders as sequential output placeholders.
	// len(parts) == len(argNums)+1
	parts []string
	// argNums are the 1-based input SQL parameter numbers in order of appearance.
	// args[argNums[i]-1] provides the value for the corresponding placeholder.
	argNums []int
	// condIdxs are 0-based indices into the args slice passed to Build.
	// All referenced args must be "active" (non-nil pointer / true bool)
	// for this segment to be included. Empty means always include.
	condIdxs []int
}

// dynCompiledQuery is a pre-parsed dynamic SQL query.
// Create one at package level with dynCompile and reuse it across calls.
type dynCompiledQuery struct {
	segs []dynCompiledSeg
}

// dynCompile parses an annotated SQL string (containing -- :if $N markers)
// into a dynCompiledQuery. Call this once at package initialisation time
// and store the result in a package-level variable.
func dynCompile(annotatedSQL string) *dynCompiledQuery {
	var segs []dynCompiledSeg
	var staticBuf strings.Builder
	nextArgNum := 1

	flushStatic := func() {
		if staticBuf.Len() == 0 {
			return
		}
		parts, argNums := dynSplitPlaceholders(staticBuf.String(), &nextArgNum)
		segs = append(segs, dynCompiledSeg{parts: parts, argNums: argNums})
		staticBuf.Reset()
	}

	rest := annotatedSQL
	firstLine := true

	for rest != "" {
		var line string
		if i := strings.IndexByte(rest, '\n'); i >= 0 {
			line, rest = rest[:i], rest[i+1:]
		} else {
			line, rest = rest, ""
		}

		sep := "\n"
		if firstLine {
			sep = ""
			firstLine = false
		}

		trimmed := strings.TrimSpace(line)

		// Standalone block annotation: "-- :if $N" — the next line is conditional.
		if after, ok := strings.CutPrefix(trimmed, "-- :if $"); ok && after != "" {
			n := dynParseInt(after, len(after))
			if n > 0 {
				flushStatic()
				condIdx := n - 1
				// Read and process next line.
				if rest != "" {
					var nextLine string
					if i := strings.IndexByte(rest, '\n'); i >= 0 {
						nextLine, rest = rest[:i], rest[i+1:]
					} else {
						nextLine, rest = rest, ""
					}
					condIdxs, cleaned := dynExtractCondIdxs(nextLine)
					condIdxs = append([]int{condIdx}, condIdxs...)
					parts, argNums := dynSplitPlaceholders("\n"+cleaned, &nextArgNum)
					segs = append(segs, dynCompiledSeg{
						parts:    parts,
						argNums:  argNums,
						condIdxs: condIdxs,
					})
				}
				continue
			}
		}

		// Inline annotation(s): "text -- :if $N [-- :if $M ...]"
		if condIdxs, cleaned := dynExtractCondIdxs(line); len(condIdxs) > 0 {
			flushStatic()
			parts, argNums := dynSplitPlaceholders(sep+cleaned, &nextArgNum)
			segs = append(segs, dynCompiledSeg{
				parts:    parts,
				argNums:  argNums,
				condIdxs: condIdxs,
			})
			continue
		}

		// Unconditional line: accumulate into the static buffer.
		staticBuf.WriteString(sep)
		staticBuf.WriteString(line)
	}

	flushStatic()
	return &dynCompiledQuery{segs: segs}
}

// Build applies the pre-compiled filter to args and returns the final SQL
// and the trimmed args slice. The method is safe to call concurrently.
//
// Numbered output placeholders reuse repeated input parameters. MySQL uses
// positional question-mark placeholders, so repeated parameters are repeated.
func (q *dynCompiledQuery) Build(args []any) (string, []any) {
	var b strings.Builder
	var outArgs []any
	n := 1
	argIdxToNs := make(map[int][]int) // input argIdx (0-based) -> output $N values

	for _, seg := range q.segs {
		// Check all conditions.
		active := true
		for _, idx := range seg.condIdxs {
			if idx >= len(args) || !dynArgActive(args[idx]) {
				active = false
				break
			}
		}
		if !active {
			continue
		}

		// Write text parts interleaved with sequential $N placeholders.
		for i, part := range seg.parts {
			if before, isSlice := dynSlicePrefix(part); isSlice {
				b.WriteString(before)
				argIdx := seg.argNums[i] - 1
				if dynQuestionMarkPlaceholders {
					if argIdx >= 0 && argIdx < len(args) {
						dynWriteSlice(&b, &outArgs, args[argIdx], &n)
					} else {
						b.WriteString("NULL")
					}
				} else if existing, ok := argIdxToNs[argIdx]; ok {
					dynWritePlaceholders(&b, existing)
				} else if argIdx >= 0 && argIdx < len(args) {
					argIdxToNs[argIdx] = dynWriteSlice(&b, &outArgs, args[argIdx], &n)
				} else {
					b.WriteString("NULL")
					argIdxToNs[argIdx] = nil
				}
				continue
			}
			b.WriteString(part)
			if i < len(seg.argNums) {
				argIdx := seg.argNums[i] - 1
				if existing, ok := argIdxToNs[argIdx]; ok && !dynQuestionMarkPlaceholders {
					// Same input parameter already emitted; reuse its output placeholder.
					dynWritePlaceholder(&b, existing[0])
				} else {
					dynWritePlaceholder(&b, n)
					argIdxToNs[argIdx] = []int{n}
					n++
					if argIdx >= 0 && argIdx < len(args) {
						outArgs = append(outArgs, args[argIdx])
					}
				}
			}
		}
	}

	return dynFinalizeQuery(b.String()), outArgs
}

func dynWritePlaceholders(b *strings.Builder, nums []int) {
	for i, n := range nums {
		if i > 0 {
			b.WriteByte(',')
		}
		dynWritePlaceholder(b, n)
	}
}

func dynWritePlaceholder(b *strings.Builder, n int) {
	if dynQuestionMarkPlaceholders {
		b.WriteByte('?')
		return
	}
	b.WriteByte('$')
	dynWriteInt(b, n)
}

func dynSlicePrefix(part string) (string, bool) {
	start := strings.LastIndex(part, "/*SLICE:")
	if start == -1 || !strings.HasSuffix(part, "*/") {
		return part, false
	}
	return part[:start], true
}

func dynWriteSlice(b *strings.Builder, outArgs *[]any, arg any, n *int) []int {
	values := reflect.ValueOf(arg)
	if values.Kind() != reflect.Slice || values.Len() == 0 {
		b.WriteString("NULL")
		return nil
	}
	nums := make([]int, values.Len())
	for i := range values.Len() {
		if i > 0 {
			b.WriteByte(',')
		}
		nums[i] = *n
		dynWritePlaceholder(b, *n)
		*n++
		*outArgs = append(*outArgs, values.Index(i).Interface())
	}
	return nums
}

// dynExtractCondIdxs extracts all " -- :if $N" annotations from line,
// returning the 0-based condition indices and the cleaned line text.
func dynExtractCondIdxs(line string) (condIdxs []int, cleaned string) {
	idx := strings.Index(line, " -- :if $")
	if idx == -1 {
		return nil, line
	}
	cleaned = strings.TrimRight(line[:idx], " \t")
	tail := line[idx:]
	for {
		i := strings.Index(tail, " -- :if $")
		if i == -1 {
			break
		}
		numStart := i + 9 // len(" -- :if $")
		numEnd := numStart
		for numEnd < len(tail) && tail[numEnd] >= '0' && tail[numEnd] <= '9' {
			numEnd++
		}
		if numEnd > numStart {
			if n := dynParseInt(tail[numStart:numEnd], numEnd-numStart); n > 0 {
				condIdxs = append(condIdxs, n-1)
			}
		}
		tail = tail[i+1:]
	}
	return condIdxs, cleaned
}

// dynSplitPlaceholders splits text at numbered $N and ?N input placeholders.
// For MySQL, bare ? input placeholders are numbered by appearance. Other bare
// markers are preserved; Build emits driver-appropriate output placeholders.
// Returns parts (len = len(argNums)+1) and 1-based argNums.
func dynSplitPlaceholders(text string, nextArgNum *int) (parts []string, argNums []int) {
	// Fast path: scan without a Builder when every placeholder marker is followed by digits.
	// Fall back to a Builder only when a bare marker is found.
	var buf *strings.Builder
	for {
		i := strings.IndexAny(text, "$?")
		if i == -1 {
			if buf != nil {
				buf.WriteString(text)
			}
			break
		}
		j := i + 1
		for j < len(text) && text[j] >= '0' && text[j] <= '9' {
			j++
		}
		if j == i+1 && !(dynQuestionMarkPlaceholders && text[i] == '?') {
			// Placeholder marker not followed by digit; preserve the text.
			if buf == nil {
				buf = &strings.Builder{}
			}
			buf.WriteString(text[:i+1])
			text = text[i+1:]
			continue
		}
		n := *nextArgNum
		if j > i+1 {
			n = dynParseInt(text[i+1:j], j-i-1)
		}
		if n <= 0 {
			if buf != nil {
				buf.WriteString(text[:j])
			}
			text = text[j:]
			continue
		}
		if dynQuestionMarkPlaceholders && n >= *nextArgNum {
			*nextArgNum = n + 1
		}
		if buf != nil {
			buf.WriteString(text[:i])
			parts = append(parts, buf.String())
			buf.Reset()
		} else {
			parts = append(parts, text[:i])
		}
		argNums = append(argNums, n)
		text = text[j:]
	}
	if buf != nil {
		parts = append(parts, buf.String())
	} else {
		parts = append(parts, text)
	}
	return parts, argNums
}

// dynFinalizeQuery cleans up the output SQL after conditional lines have been
// removed. It loops until stable, handling cascading cases such as:
//   - trailing comma on the new last line  → strip the comma
//   - orphaned clause keyword (WHERE, ORDER BY, GROUP BY, HAVING) → remove it
func dynFinalizeQuery(query string) string {
	for {
		// Find the end of the last non-empty line.
		end := len(query)
		for end > 0 && (query[end-1] == ' ' || query[end-1] == '\t' || query[end-1] == '\n') {
			end--
		}
		if end == 0 {
			return query
		}
		// Find start of last non-empty line.
		start := end
		for start > 0 && query[start-1] != '\n' {
			start--
		}
		trimmed := strings.TrimSpace(query[start:end])

		// Strip trailing comma.
		if len(trimmed) > 0 && trimmed[len(trimmed)-1] == ',' {
			commaPos := strings.LastIndexByte(query[start:end], ',')
			if commaPos >= 0 {
				query = query[:start+commaPos] + query[start+commaPos+1:]
			}
			continue // re-evaluate after removal
		}

		// Remove orphaned SQL clause keywords.
		if strings.EqualFold(trimmed, "ORDER BY") ||
			strings.EqualFold(trimmed, "WHERE") ||
			strings.EqualFold(trimmed, "GROUP BY") ||
			strings.EqualFold(trimmed, "HAVING") {
			newEnd := start
			for newEnd > 0 && (query[newEnd-1] == '\n' || query[newEnd-1] == ' ' || query[newEnd-1] == '\t') {
				newEnd--
			}
			query = query[:newEnd]
			continue // re-evaluate after removal
		}

		break // nothing changed
	}
	return query
}

// DynSQL is a pre-compiled dynamic SQL query.
// Use CompileDynSQL to create one at package level for maximum performance.
type DynSQL = dynCompiledQuery

// CompileDynSQL parses an annotated SQL string (containing -- :if $N markers)
// once and returns a *DynSQL whose Build method can be called repeatedly
// with no per-call string scanning.
func CompileDynSQL(annotatedSQL string) *DynSQL {
	return dynCompile(annotatedSQL)
}

// DynamicSQL processes a SQL query with -- :if $N annotations at runtime.
// Prefer dynCompile + Build for repeated calls; DynamicSQL is provided for
// one-off use and backward compatibility.
//
// For each annotated line, it checks args[N-1] (N is 1-based, matching $N):
//   - nil pointer → skip the line
//   - false bool  → skip the line
//   - otherwise   → keep the line
//
// After filtering, remaining $N placeholders are renumbered sequentially and
// the args slice is trimmed to match, so the query is always valid.
func DynamicSQL(query string, args []any) (string, []any) {
	return dynCompile(query).Build(args)
}

// dynParseInt parses a non-negative integer from s[0:length] without allocations.
// Returns -1 if the string contains non-digit characters.
func dynParseInt(s string, length int) int {
	n := 0
	for i := 0; i < length; i++ {
		c := s[i]
		if c < '0' || c > '9' {
			return -1
		}
		n = n*10 + int(c-'0')
	}
	return n
}

// dynWriteInt writes a positive integer to buf without allocations for values < 10.
func dynWriteInt(buf *strings.Builder, n int) {
	if n < 10 {
		buf.WriteByte(byte('0' + n))
	} else if n < 100 {
		buf.WriteByte(byte('0' + n/10))
		buf.WriteByte(byte('0' + n%10))
	} else {
		var tmp [20]byte
		i := len(tmp)
		for n > 0 {
			i--
			tmp[i] = byte('0' + n%10)
			n /= 10
		}
		buf.Write(tmp[i:])
	}
}

func dynArgActive(arg any) bool {
	if arg == nil {
		return false
	}
	switch v := arg.(type) {
	case bool:
		return v
	case *string:
		return v != nil
	case *int:
		return v != nil
	case *int32:
		return v != nil
	case *int64:
		return v != nil
	case *float64:
		return v != nil
	case *bool:
		return v != nil
	}
	v := reflect.ValueOf(arg)
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface, reflect.Slice:
		return !v.IsNil()
	default:
		return true
	}
}
